import { useState, useEffect } from "react";
import ReactMarkdown from "react-markdown";import remarkGfm from "remark-gfm";import rehypeRaw from "rehype-raw";import rehypeSanitize from "rehype-sanitize";
import { EXPANSION_MANIFEST } from "../data/generatedExpansionManifest";
import type { Result, PlotArtifact } from "../data/ExpansionTypes";
import "../expansion.css";
const BASE=import.meta.env.BASE_URL||"/";const mdCache=new Map<string,string>();const PAGE=5;
const CORNER_COLORS:Record<string,string>={t:"var(--accent,#64748b)",s:"#f97316",f:"#22c55e"};
const C_ORDER=["t","s","f"] as const;

function Kpi({l,v}:{l:string;v:string|number}){return<div className="ex-kpi"><span className="ex-kpi-value">{typeof v==="number"?v:v}</span><span className="ex-kpi-label">{l}</span></div>}
function PlotCard({p,featured,onClick}:{p:PlotArtifact;featured?:boolean;onClick:()=>void}){const c=p.caption;const wide=p.aspectRatio&&p.aspectRatio>1.8;return<div className={`ex-plot-card ${featured?"ex-plot-card--featured":""} ${wide?"ex-plot-card--wide":""}`} onClick={onClick}><div className="ex-plot-img"><img src={BASE+p.displayUrl!} alt={c?.title||p.name} loading="lazy"/></div><div className="ex-plot-body"><strong className="ex-plot-title">{c?.title||p.name}</strong>{c&&<p className="ex-plot-what">{c.what}</p>}{c&&<p className="ex-plot-why hint">{c.why}</p>}<div className="ex-plot-meta">{c?.device&&<span className="ex-badge">{c.device}</span>}<span className="hint">{p.format?.toUpperCase()}·{p.size}·{p.width}×{p.height}</span></div><details className="ex-plot-detail"><summary>Details</summary><code>{p.relPath}</code>·hash:<code>{p.hash}</code></details></div></div>;}
function PagedTable({cols,rows}:{cols:string[];rows:Record<string,string>[]}){const[pg,setPg]=useState(0);const t=Math.ceil(rows.length/PAGE);const s=rows.slice(pg*PAGE,(pg+1)*PAGE);return<div className="ex-paged"><div className="ex-paged-bar"><span>Showing {s.length} of {rows.length}</span><div className="ex-paged-nav"><button className="benchmark-btn" disabled={pg===0} onClick={()=>setPg(0)}>««</button><button className="benchmark-btn" disabled={pg===0} onClick={()=>setPg(p=>p-1)}>«</button><span className="hint">Page {pg+1}/{t||1}</span><button className="benchmark-btn" disabled={pg>=t-1} onClick={()=>setPg(p=>p+1)}>»</button><button className="benchmark-btn" disabled={pg>=t-1} onClick={()=>setPg(t-1)}>»»</button></div></div><div className="tr-table-wrap"><table className="tr-table"><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{s.map((r,i)=><tr key={i}>{cols.map(c=><td key={c}>{r[c]||""}</td>)}</tr>)}</tbody></table></div></div>;}
function Lightbox({plots,index,onClose}:{plots:PlotArtifact[];index:number;onClose:()=>void}){const[idx,setIdx]=useState(index);const[zoom,setZoom]=useState(1);useEffect(()=>{const k=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();if(e.key==="ArrowRight")setIdx(p=>Math.min(p+1,plots.length-1));if(e.key==="ArrowLeft")setIdx(p=>Math.max(p-1,0));if(e.key==="+"||e.key==="=")setZoom(z=>+(z+0.25).toFixed(2));if(e.key==="-")setZoom(z=>Math.max(0.25,+(z-0.25).toFixed(2)));if(e.key==="0")setZoom(1);};window.addEventListener("keydown",k);return()=>window.removeEventListener("keydown",k);},[plots.length,onClose]);const p=plots[idx];if(!p?.displayUrl)return null;return<div className="ex-lightbox" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><button className="ex-lightbox-close" onClick={onClose}>×</button><div className="ex-lightbox-nav"><button disabled={idx===0} onClick={e=>{e.stopPropagation();setIdx(x=>Math.max(0,x-1));}}>‹</button><span>{idx+1}/{plots.length}</span><button disabled={idx>=plots.length-1} onClick={e=>{e.stopPropagation();setIdx(x=>Math.min(plots.length-1,x+1));}}>›</button></div><div className="ex-lightbox-zoom"><button onClick={()=>setZoom(z=>+(z-0.25).toFixed(2))}>−</button><button onClick={()=>setZoom(1)}>{Math.round(zoom*100)}%</button><button onClick={()=>setZoom(z=>+(z+0.25).toFixed(2))}>+</button></div><img src={BASE+p.displayUrl} alt={p.name} style={{transform:`scale(${zoom})`,cursor:zoom>1?"zoom-out":"zoom-in",maxWidth:"90vw",maxHeight:"72vh",objectFit:"contain"}} onClick={e=>{e.stopPropagation();setZoom(z=>z>1?1:2);}}/><div className="ex-lightbox-info"><strong>{p.caption?.title||p.name}</strong><a href={BASE+p.displayUrl} download className="benchmark-btn">Download</a></div></div>;}
function ReportSections({content,plots}:{content:string;plots:PlotArtifact[]}){const[expandAll,setExpandAll]=useState(false);const secs=content.split(/^##\s+/m).filter(Boolean).map(sec=>{const nl=sec.indexOf("\n");return{title:nl>0?sec.slice(0,nl).trim():"Section",content:sec.slice(nl+1)}});const[tocOpen,setTocOpen]=useState(false);return<div>{<details className="ex-toc" open={tocOpen}><summary onClick={()=>setTocOpen(!tocOpen)}>Table of Contents</summary><ul>{secs.map((s,i)=><li key={i}><a href={`#ex-sec-${i}`}>{s.title}</a></li>)}</ul></details>}<button className="benchmark-btn" onClick={()=>setExpandAll(e=>!e)} style={{marginBottom:"0.5rem"}}>{expandAll?"Collapse all":"Expand all report"}</button>{secs.map((s,i)=>{const[open,setOpen]=useState(expandAll||i===0||/overview|corner summary/i.test(s.title));const preview=s.content.slice(0,250);const relevantPlots=plots.filter(p=>s.title.toLowerCase().includes("corner")?(p.section==="iv"||p.section==="cv"):s.title.toLowerCase().includes("monte carlo")?p.section==="mc":false);return<div key={i} id={`ex-sec-${i}`} className="ex-report-section"><h3 className="ex-report-section-title" onClick={()=>setOpen(!open)}><span className="ex-accordion-icon">{open?"▾":"▸"}</span>{s.title}</h3>{!open&&<div className="tr-md"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeRaw,rehypeSanitize]}>{preview+"\n\n..."}</ReactMarkdown></div>}{open&&<div className="tr-md"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeRaw,rehypeSanitize]} components={{table:({children})=><div className="tr-table-wrap"><table className="tr-table">{children}</table></div>,img:({src,alt}:any)=>{const pt=plots.find(x=>src?.includes(x.name));return<img src={pt?.displayUrl?BASE+pt.displayUrl:src} alt={alt||""} loading="lazy" style={{maxWidth:"100%"}}/>;}}}>{s.content}</ReactMarkdown>{relevantPlots.length>0&&<div style={{marginTop:"0.5rem"}}>{relevantPlots.map(rp=><PlotCard key={rp.relPath} p={rp} onClick={()=>{}}/>)}</div>}</div>}{!open&&<button className="benchmark-btn ex-read-more" onClick={()=>setOpen(true)}>Read full section</button>}</div>})}</div>;}

export function ExpansionPage(){const m=EXPANSION_MANIFEST;const[sid,setSid]=useState(m.defaultResultId);const[lb,setLb]=useState<number|null>(null);const[signMode,setSignMode]=useState<"signed"|"mag">("signed");const r=m.results.find(x=>x.resultId===sid);if(!r)return<div className="ex-page"><Selector r={m.results} sid={sid} onS={setSid}/><div className="chart-card"><p className="hint">No result.</p></div></div>;
const feat=r.plots.filter(p=>p.section==="iv").slice(0,1).concat(r.plots.filter(p=>p.section==="cv").slice(0,1)).concat(r.plots.filter(p=>p.section==="mc").slice(0,1)).slice(0,3);
const [md,setMd]=useState<string|null>(null);const rpt=r.reports[0];
useEffect(()=>{if(!rpt?.fetchUrl)return;const u=BASE+rpt.fetchUrl;if(mdCache.has(u)){setMd(mdCache.get(u)!);return}let c=false;fetch(u).then(r=>r.text()).then(t=>{if(!c){mdCache.set(u,t);setMd(t)}});return()=>{c=true}},[sid]);
const delta=(v:number|undefined,ref:number|undefined)=>{if(v===undefined||ref===undefined||ref===0)return"N/A";const d=signMode==="signed"?v-ref:Math.abs(v)-Math.abs(ref);const pct=((d)/(Math.abs(ref)||1)*100).toFixed(1);return`${d>=0?"+":""}${d.toExponential(2)} (${pct}%)`};
return<div className="ex-page"><Selector r={m.results} sid={sid} onS={setSid}/>
{/* Compact KPI */}<div className="chart-card ex-compact"><h2 className="ex-compact-title">{r.title}</h2><p className="hint" style={{color:"var(--warn,#ff9f0a)"}}>⚠ Derived from a TT model; not foundry-certified corners</p><div className="ex-kpi-grid"><Kpi l="Source TT" v={r.kpis.sourceTT}/><Kpi l="nσ" v={r.kpis.sigma}/><Kpi l="Devices" v={r.kpis.devices.length}/><Kpi l="Coverage" v={r.kpis.coverage}/><Kpi l="MC Samples" v={r.kpis.mcSamples}/><Kpi l="Distribution" v={r.kpis.distribution}/><Kpi l="Seed" v={r.kpis.seed}/></div></div>
{/* Featured */}{feat.length>0&&<div className="chart-card ex-section"><h2 className="ex-section-heading">Featured Plots</h2><div className={`ex-featured-grid ${feat.length<=2?"ex-featured-grid--2":""}`}>{feat.map(p=><PlotCard key={p.relPath} p={p} featured onClick={()=>setLb(r.plots.indexOf(p))}/>)}</div></div>}
{/* Corner Comparison */}<div className="chart-card ex-section"><h2 className="ex-section-heading">Corner Comparison</h2><div style={{marginBottom:"0.5rem",display:"flex",gap:"0.5rem",alignItems:"center"}}><button className="benchmark-btn" onClick={()=>setSignMode(m=>m==="signed"?"mag":"signed")}>Mode: {signMode==="signed"?"Signed values":"Magnitude"}</button></div>{C_ORDER.filter(c=>r.corners.some(co=>co.corner===c)).map(c=>{const cos=r.corners.filter(co=>co.corner===c);const ref=r.corners.filter(co=>co.corner==="t");return<div key={c} className="ex-corner-group"><h3 style={{color:CORNER_COLORS[c]}}>Corner {c.toUpperCase()}</h3><div className="tr-table-wrap"><table className="tr-table"><thead><tr><th>Device</th><th>Ion</th><th>Ioff</th><th>Ion/Ioff</th><th>Idens</th><th>Vth</th></tr></thead><tbody>{cos.map(co=>{const rt=ref.find(x=>x.device===co.device);return<tr key={co.device}><td><code>{co.device}</code></td>{(["ion","ioff","ionIoff","idens","vth"]as const).map(k=><td key={k} className="tr-num">{co[k]!==undefined?co[k]:"N/A"}<span className="hint" style={{display:"block",fontSize:"0.6rem"}}>{c!=="t"?delta(co[k],rt?.[k]):""}</span></td>)}</tr>})}</tbody></table></div></div>})}</div>
{/* Monte Carlo */}<div className="chart-card ex-section"><h2 className="ex-section-heading">Monte Carlo Statistics</h2>{r.mcStats.map(s=><div key={s.device} className="ex-mc-device"><h3>{s.device} <span className="hint">({s.samples} samples, Id mean: {s.idMean?.toExponential(2)}, 1σ: {s.idSigma?.toExponential(2)})</span></h3><PagedTable cols={["Parameter","mean","1σ"]} rows={s.params.map(p=>({Parameter:p.name,mean:p.mean.toExponential(4),"1σ":p.sigma.toExponential(4)}))}/></div>)}</div>
{/* IV/CV Plots */}{(["iv","cv"]as const).map(sec=>{const secPlots=r.plots.filter(p=>p.section===sec);if(!secPlots.length)return null;return<div key={sec} className="chart-card ex-section"><h2 className="ex-section-heading">{sec==="iv"?"IV Characteristics":"CV Characteristics"} <span className="hint">({secPlots.length})</span></h2><div className="ex-plot-gallery">{secPlots.map(p=><PlotCard key={p.relPath} p={p} onClick={()=>setLb(r.plots.indexOf(p))}/>)}</div></div>})}
{/* MC Plots */}{r.plots.filter(p=>p.section==="mc").length>0&&<div className="chart-card ex-section"><h2 className="ex-section-heading">MC Distributions</h2><div className="ex-plot-gallery">{r.plots.filter(p=>p.section==="mc").map(p=><PlotCard key={p.relPath} p={p} onClick={()=>setLb(r.plots.indexOf(p))}/>)}</div></div>}
{/* Full Report */}<div className="chart-card ex-section"><h2 className="ex-section-heading">SUMMARY.md</h2>{md===null?<p className="hint">Loading…</p>:md===undefined?<p className="hint">Failed to load.</p>:<ReportSections content={md} plots={r.plots}/>}{rpt?.fetchUrl&&<a href={BASE+rpt.fetchUrl} download className="benchmark-btn">⬇ Download</a>}</div>
{/* Artifacts */}<div className="chart-card ex-section"><h2 className="ex-section-heading">Artifacts</h2><PagedTable cols={["Name","Type","Path","Size","Hash"]} rows={[...r.reports.map(f=>({Name:f.name,Type:"report",Path:f.relPath,Size:f.size,Hash:f.hash})),...r.plots.map(f=>({Name:f.name,Type:"plot",Path:f.relPath,Size:f.size,Hash:f.hash})),...r.dataArtifacts.map(f=>({Name:f.name,Type:"data",Path:f.relPath,Size:f.size,Hash:f.hash})),...r.otherArtifacts.map(f=>({Name:f.name,Type:"other",Path:f.relPath,Size:f.size,Hash:f.hash}))]}/></div>
{lb!==null&&<Lightbox plots={r.plots} index={lb} onClose={()=>setLb(null)}/>}</div>;}
function Selector({r:results,sid,onS}:{r:Result[];sid:string;onS:(id:string)=>void}){return<div className="chart-card ex-selector"><h2>Explore expansion results</h2><p className="hint">Select a result directory — corners, Monte Carlo, plots update below.</p><div className="ex-selector-grid"><label className="axis-picker">Result<select value={sid} onChange={e=>onS(e.target.value)}>{results.map(r=><option key={r.resultId} value={r.resultId}>{r.title}</option>)}</select></label><label className="axis-picker">Model<span className="benchmark-readonly">{results.find(r=>r.resultId===sid)?.model||"—"}</span></label></div></div>;}
