import { useState, useEffect } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeRaw from "rehype-raw";
import rehypeSanitize from "rehype-sanitize";
import { REDUCTION_MANIFEST } from "../data/generatedReductionManifest";
import type { ReductionResult, PlotArtifact, IterationEntry } from "../data/ReductionTypes";
import "../reduction.css";

const BASE = import.meta.env.BASE_URL || "/";
const mdCache = new Map<string, string>();
const PAGE = 5;

/* ─── KPI ─── */
function Kpi({label,v,note}:{label:string;v:string|number;note?:string}){return <div className="rd-kpi"><span className="rd-kpi-value">{typeof v==="number"&&v<1?`${(v*100).toFixed(1)}%`:v}</span><span className="rd-kpi-label">{label}</span>{note&&<span className="rd-kpi-note">{note}</span>}</div>;}

/* ─── PagedTable ─── */
function PagedTable({cols,rows}:{cols:string[];rows:Record<string,string>[]}){const[pg,setPg]=useState(0);const t=Math.ceil(rows.length/PAGE);const s=rows.slice(pg*PAGE,(pg+1)*PAGE);return<div className="rd-paged"><div className="rd-paged-bar"><span>Showing {s.length} of {rows.length}</span><div className="rd-paged-nav"><button className="benchmark-btn" disabled={pg===0} onClick={()=>setPg(0)}>««</button><button className="benchmark-btn" disabled={pg===0} onClick={()=>setPg(p=>p-1)}>«</button><span className="hint">Page {pg+1}/{t||1}</span><button className="benchmark-btn" disabled={pg>=t-1} onClick={()=>setPg(p=>p+1)}>»</button><button className="benchmark-btn" disabled={pg>=t-1} onClick={()=>setPg(t-1)}>»»</button></div></div><div className="tr-table-wrap"><table className="tr-table"><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{s.map((r,i)=><tr key={i}>{cols.map(c=><td key={c}>{r[c]||""}</td>)}</tr>)}</tbody></table></div></div>;}

/* ─── PlotCard ─── */
function PlotCard({p,featured,onClick}:{p:PlotArtifact;featured?:boolean;onClick:()=>void}){const c=p.caption;const wide=p.aspectRatio&&p.aspectRatio>1.8;return<div className={`rd-plot-card ${featured?"rd-plot-card--featured":""} ${wide?"rd-plot-card--wide":""}`} onClick={onClick}><div className="rd-plot-img"><img src={BASE+p.displayUrl!} alt={c?.title||p.name} loading="lazy"/></div><div className="rd-plot-body"><strong className="rd-plot-title">{c?.title||p.name}</strong>{c&&<p className="rd-plot-what">{c.what}</p>}{c&&<p className="rd-plot-why hint">{c.why}</p>}<div className="rd-plot-meta"><span className="hint">{p.format?.toUpperCase()}·{p.size}·{p.width}×{p.height}</span></div><details className="rd-plot-detail"><summary>Details</summary><code>{p.relPath}</code>·hash:<code>{p.hash}</code></details></div></div>;}

/* ─── Lightbox ─── */
function Lightbox({plots,index,onClose}:{plots:PlotArtifact[];index:number;onClose:()=>void}){const[idx,setIdx]=useState(index);const[zoom,setZoom]=useState(1);useEffect(()=>{const k=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();if(e.key==="ArrowRight")setIdx(p=>Math.min(p+1,plots.length-1));if(e.key==="ArrowLeft")setIdx(p=>Math.max(p-1,0));if(e.key==="+"||e.key==="=")setZoom(z=>+(z+0.25).toFixed(2));if(e.key==="-")setZoom(z=>Math.max(0.25,+(z-0.25).toFixed(2)));if(e.key==="0")setZoom(1);};window.addEventListener("keydown",k);return()=>window.removeEventListener("keydown",k);},[plots.length,onClose]);const p=plots[idx];if(!p?.displayUrl)return null;return<div className="tr-lightbox" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><button className="tr-lightbox-close" onClick={onClose}>×</button><div className="tr-lightbox-nav"><button disabled={idx===0} onClick={e=>{e.stopPropagation();setIdx(x=>Math.max(0,x-1));}}>‹</button><span>{idx+1}/{plots.length}</span><button disabled={idx>=plots.length-1} onClick={e=>{e.stopPropagation();setIdx(x=>Math.min(plots.length-1,x+1));}}>›</button></div><div className="tr-lightbox-zoom"><button onClick={()=>setZoom(z=>+(z-0.25).toFixed(2))}>−</button><button onClick={()=>setZoom(1)}>{Math.round(zoom*100)}%</button><button onClick={()=>setZoom(z=>+(z+0.25).toFixed(2))}>+</button></div><img src={BASE+p.displayUrl} alt={p.name} style={{transform:`scale(${zoom})`,cursor:zoom>1?"zoom-out":"zoom-in",maxWidth:"90vw",maxHeight:"72vh",objectFit:"contain"}} onClick={e=>{e.stopPropagation();setZoom(z=>z>1?1:2);}}/><div className="tr-lightbox-info"><strong>{p.caption?.title||p.name}</strong><a href={BASE+p.displayUrl} download className="benchmark-btn">Download</a></div></div>;}

/* ─── IterationExplorer ─── */
function IterationExplorer({iterations}:{iterations:IterationEntry[]}){const[idx,setIdx]=useState(0);const it=iterations[idx];if(!iterations.length)return<p className="hint">No iteration data.</p>;return<div className="rd-iter"><div className="rd-iter-slider"><span>Iteration {it.iteration}</span><input type="range" min={0} max={iterations.length-1} value={idx} onChange={e=>setIdx(+e.target.value)}/></div><div className="rd-iter-grid">{["totalError","parameterCount","timestamp"].map(k=><div key={k} className="rd-iter-cell"><strong>{k}</strong><span>{String((it as any)[k]||"—")}</span></div>)}</div>{it.simulationErrors&&<details className="rd-iter-errors"><summary>Simulation Errors</summary><div className="tr-table-wrap"><table className="tr-table"><tbody>{Object.entries(it.simulationErrors).map(([k,v])=><tr key={k}><td>{k}</td><td className="tr-num">{String(v)}</td></tr>)}</tbody></table></div></details>}</div>;}

/* ─── Selector ─── */
function Selector({results,selectedId,onSelect}:{results:ReductionResult[];selectedId:string;onSelect:(id:string)=>void}){return<div className="chart-card rd-selector"><h2>Explore reduction results</h2><p className="hint">Select a result to view its KPI, reports, plots, and artifacts.</p><div className="rd-selector-grid"><label className="axis-picker">Result<select value={selectedId} onChange={e=>onSelect(e.target.value)}>{results.map(r=><option key={r.resultId} value={r.resultId}>{r.title}</option>)}</select></label><label className="axis-picker">Model<span className="benchmark-readonly">{results.find(r=>r.resultId===selectedId)?.model||"—"}</span></label><label className="axis-picker">Device<span className="benchmark-readonly">{results.find(r=>r.resultId===selectedId)?.device||"—"}</span></label></div></div>;}

/* ─── Report section (accordion) ─── */
function ReportSection({title,content,defaultOpen}:{title:string;content:string;defaultOpen?:boolean}){const[open,setOpen]=useState(defaultOpen||false);const preview=content.slice(0,250);return<div className="rd-report-section"><h3 className="rd-report-section-title" onClick={()=>setOpen(!open)}><span className="rd-accordion-icon">{open?"▾":"▸"}</span>{title}</h3>{!open&&<div className="tr-md"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeRaw,rehypeSanitize]}>{preview+"\n\n..."}</ReactMarkdown></div>}{open&&<div className="tr-md"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeRaw,rehypeSanitize]} components={{table:({children})=><div className="tr-table-wrap"><table className="tr-table">{children}</table></div>,th:({children})=><th>{children}</th>,td:({children})=><td>{children}</td>,code:({className,children}:any)=>className?.includes("language-")?<details className="tr-code-block"><summary>{className.replace("language-","")||"code"}</summary><pre><code className={className}>{children}</code></pre></details>:<code>{children}</code>,img:({src,alt}:any)=><img src={src} alt={alt||""} loading="lazy" style={{maxWidth:"100%"}}/>,a:({href,children}:any)=><a href={href} target="_blank" rel="noopener">{children}</a>}}>{content}</ReactMarkdown></div>}{!open&&<button className="benchmark-btn rd-read-more" onClick={()=>setOpen(true)}>Read full section</button>}</div>;}

/* ═══════════════════════════════════════════════════════════════════ */
export function ReductionPage(){const m=REDUCTION_MANIFEST;const[sid,setSid]=useState(m.defaultResultId);const[lb,setLb]=useState<number|null>(null);const[expandAll,setExpandAll]=useState(false);const r=m.results.find(x=>x.resultId===sid);if(!r)return<div className="rd-page"><Selector results={m.results} selectedId={sid} onSelect={setSid}/><div className="chart-card"><p className="hint">No result selected.</p></div></div>;

const k=r.kpis;
const featured=r.plots.filter(p=>p.section==="accuracy"||p.section==="parameter").slice(0,2);
const paramPlots=r.plots.filter(p=>p.section==="parameter");const accuracyPlots=r.plots.filter(p=>p.section==="accuracy");const convPlots=r.plots.filter(p=>p.section==="convergence");const perfPlots=r.plots.filter(p=>p.section==="performance");
const [mdContents,setMdContents]=useState<Record<string,string|null>>({});

useEffect(()=>{for(const rpt of r.reports){if(!rpt.fetchUrl)continue;const url=BASE+rpt.fetchUrl;if(mdCache.has(url)){setMdContents(p=>({...p,[rpt.name]:mdCache.get(url)!}));continue;}fetch(url).then(r=>r.text()).then(t=>{mdCache.set(url,t);setMdContents(p=>({...p,[rpt.name]:t}));});}},[sid]);

return<div className="rd-page"><Selector results={m.results} selectedId={sid} onSelect={setSid}/>

{/* 1. Compact Summary */}<div className="chart-card rd-compact"><h2 className="rd-compact-title">{r.title}</h2><p className="hint">{r.description}</p><div className="rd-kpi-grid"><Kpi label="Original Params" v={k.originalParams}/><Kpi label="Reduced Params" v={k.reducedParams}/><Kpi label="Reduction Ratio" v={k.reductionRatio}/><Kpi label="Validation Error" v={k.validationError}/><Kpi label="Error Tolerance" v={k.errorTolerance}/><Kpi label="Within Tolerance" v={k.withinTolerance?"✓ Yes":"✗ No"}/><Kpi label="Runtime" v={`${k.runtimeSeconds.toFixed(0)}s`}/><Kpi label="Optimizations" v={k.optimizationIterations} note={k.dataConsistencyNote?`Analytics: ${k.analyticsIterations}, Tracked: ${k.trackedIterations}`:undefined}/></div>{k.dataConsistencyNote&&<p className="hint" style={{marginTop:"0.5rem",color:"var(--warn,#ff9f0a)"}}>⚠ {k.dataConsistencyNote}</p>}{k.analyticsIterations&&k.trackedIterations&&k.analyticsIterations!==k.trackedIterations&&<div className="rd-consistency"><strong>Data consistency note:</strong><span>Optimizer: {k.optimizationIterations} iterations</span><span>Analytics: {k.analyticsIterations} records</span><span>Tracked: {k.trackedIterations} iterations</span></div>}</div>

{/* 2. Featured Comparison */}{featured.length>0&&<div className="chart-card rd-section"><h2 className="rd-section-heading">Featured Comparison</h2><div className={`rd-featured-grid ${featured.length<=2?"rd-featured-grid--2":""}`}>{featured.map(p=><PlotCard key={p.relPath} p={p} featured onClick={()=>setLb(r.plots.indexOf(p))}/>)}</div></div>}

{/* 3-6. Thematic sections */}{[{title:"Parameter Reduction",plots:paramPlots},{title:"Accuracy & Convergence",plots:accuracyPlots.concat(convPlots)},{title:"Runtime Performance",plots:perfPlots}].map(sec=>(sec.plots.length>0?<div key={sec.title} className="chart-card rd-section"><h2 className="rd-section-heading">{sec.title}</h2><div className="rd-plot-gallery">{sec.plots.map(p=><PlotCard key={p.relPath} p={p} onClick={()=>setLb(r.plots.indexOf(p))}/>)}</div></div>:null))}

{/* 7. Iteration Explorer */}<div className="chart-card rd-section"><h2 className="rd-section-heading">Iteration Explorer</h2><IterationExplorer iterations={r.iterations}/></div>

{/* 8. Retained Parameters */}<div className="chart-card rd-section"><h2 className="rd-section-heading">Retained Parameters ({r.retainedParams.length})</h2><PagedTable cols={["Parameter","Value","Retained"]} rows={r.retainedParams.map(p=>({Parameter:p.name,Value:String(p.value),Retained:p.retained?"✓ Yes":"Removed"}))}/></div>

{/* 9. Full Reports */}<div className="chart-card rd-section"><div className="rd-report-header"><h2 className="rd-section-heading">Full Reports</h2>{r.reports.length>0&&<button className="benchmark-btn" onClick={()=>setExpandAll(e=>!e)}>{expandAll?"Collapse all":"Expand all"}</button>}</div>{r.reports.map(rpt=>(<div key={rpt.relPath} className="rd-report-entry">{<div className="rd-report-separator"><strong>{rpt.name}</strong><span className="hint">{rpt.size}·<code>{rpt.hash}</code></span>{rpt.fetchUrl&&<a href={BASE+rpt.fetchUrl} download className="benchmark-btn">⬇ Download</a>}</div>}{mdContents[rpt.name]===null?<p className="hint">Loading…</p>:mdContents[rpt.name]===undefined?<p className="hint">Failed to load.</p>:rpt.isHtml?<div dangerouslySetInnerHTML={{__html:mdContents[rpt.name]||""}}/>:((mdContents[rpt.name]||"").split(/^##\s+/m).filter(Boolean).map((sec,i)=>{const nl=sec.indexOf("\n");const title=nl>0?sec.slice(0,nl).trim():"Section";const content=sec.slice(nl+1);return<ReportSection key={i} title={title} content={content} defaultOpen={expandAll||i===0||/executive|summary|key result/i.test(title)}/>;}))}</div>))}</div>

{/* 10. Artifacts */}<div className="chart-card rd-section"><h2 className="rd-section-heading">Artifacts</h2><PagedTable cols={["Name","Type","Path","Size","Hash"]} rows={[...r.reports.map(f=>({Name:f.name,Type:"report",Path:f.relPath,Size:f.size,Hash:f.hash})),...r.plots.map(f=>({Name:f.name,Type:"plot",Path:f.relPath,Size:f.size,Hash:f.hash})),...r.dataArtifacts.map(f=>({Name:f.name,Type:"data",Path:f.relPath,Size:f.size,Hash:f.hash})),...r.otherArtifacts.map(f=>({Name:f.name,Type:"other",Path:f.relPath,Size:f.size,Hash:f.hash}))]}/></div>

{lb!==null&&<Lightbox plots={r.plots} index={lb} onClose={()=>setLb(null)}/>}</div>;}
