import { useEffect, useMemo, useRef, useState, type ChangeEvent } from "react";
import { useNavigate } from "react-router-dom";
import type { InputManifestV1, JobPlanV1, JsonPrimitive, ParameterDefinitionV1, ToolCapabilityV1 } from "../../../shared/contracts/v1";
import { createPpaDraft, getPpaCapabilities, preflightPpaDraft, startPpaJob, type PpaCapabilityResponse } from "../../api/ppa";
import { useAuth } from "../../auth/AuthContext";
import "../../digital-run.css";

type Mode = "run" | "import";
type FileRole = "rtl" | "gate_netlist" | "sdc" | "include" | "macro_lib" | "macro_lef" | "macro_gds" | "completed_run" | "ignore";
interface SelectedFile { id: string; file: File; relativePath: string; role: FileRole; sha256: string | null; }
interface SweepValue { mode: "single" | "range" | "list"; single: string; start: string; stop: string; step: string; list: string; }

const ROLES: Array<{ value: FileRole; label: string }> = [
  { value: "rtl", label: "RTL/source" }, { value: "gate_netlist", label: "Gate-level netlist" }, { value: "sdc", label: "SDC" },
  { value: "include", label: "Include/header" }, { value: "macro_lib", label: "Macro Liberty" }, { value: "macro_lef", label: "Macro LEF" },
  { value: "macro_gds", label: "Macro GDS" }, { value: "completed_run", label: "Completed-run evidence" }, { value: "ignore", label: "Do not use" },
];
function relativePath(file: File): string { return (file.webkitRelativePath || file.name).replaceAll("\\", "/").replace(/^\.\//, ""); }
function inferRole(file: File, mode: Mode): FileRole {
  if (mode === "import") return "completed_run"; const name = file.name.toLowerCase();
  if (name.endsWith(".sdc")) return "sdc"; if (name.endsWith(".lib")) return "macro_lib"; if (name.endsWith(".lef")) return "macro_lef"; if (name.endsWith(".gds")) return "macro_gds";
  if (name.endsWith(".vh") || name.endsWith(".svh")) return "include"; if (name.endsWith(".tcl") || name.endsWith(".mk") || name.endsWith(".py") || name.endsWith(".sh")) return "ignore"; return "rtl";
}
async function digest(file: File): Promise<string> { return [...new Uint8Array(await crypto.subtle.digest("SHA-256", await file.arrayBuffer()))].map((value) => value.toString(16).padStart(2, "0")).join(""); }
function displayBytes(value: number): string { return value < 1024 ? `${value} B` : value < 1048576 ? `${(value / 1024).toFixed(1)} KiB` : `${(value / 1048576).toFixed(1)} MiB`; }
function healthLabel(capability: ToolCapabilityV1): string { return capability.health === "healthy" ? `Available${capability.toolVersion ? ` · ${capability.toolVersion}` : ""}` : capability.health === "not_configured" ? "Not configured" : capability.health === "unavailable" ? "Unavailable" : "Degraded"; }

function FileButtons({ mode, onFiles }: { mode: Mode; onFiles(files: File[]): void }): JSX.Element {
  const one = useRef<HTMLInputElement>(null); const many = useRef<HTMLInputElement>(null); const folder = useRef<HTMLInputElement>(null);
  useEffect(() => folder.current?.setAttribute("webkitdirectory", ""), []);
  const changed = (event: ChangeEvent<HTMLInputElement>) => { onFiles([...event.target.files ?? []]); event.target.value = ""; };
  const accept = mode === "run" ? ".v,.sv,.vh,.svh,.sdc,.lib,.lef,.gds,.json,.tcl,.mk,.py" : ".json,.csv,.def,.gds,.spef,.rpt,.log,.tcl,.mk,.py";
  return <div className="digital-file-actions"><button type="button" onClick={() => one.current?.click()}>Choose single file</button><button type="button" onClick={() => many.current?.click()}>Choose files</button><button type="button" onClick={() => folder.current?.click()}>Choose folder</button><input hidden ref={one} type="file" accept={accept} onChange={changed} /><input hidden ref={many} type="file" accept={accept} multiple onChange={changed} /><input hidden ref={folder} type="file" multiple onChange={changed} /></div>;
}

function ParameterInput({ definition, value, onChange }: { definition: ParameterDefinitionV1; value: string; onChange(value: string): void }): JSX.Element {
  if (definition.type === "boolean") return <label>{definition.label}<input type="checkbox" checked={value === "true"} onChange={(event) => onChange(String(event.target.checked))} /><small>{definition.description}</small></label>;
  if (definition.type === "enum") return <label>{definition.label}<select value={value} onChange={(event) => onChange(event.target.value)}>{definition.enumValues.map((option) => <option key={String(option)} value={String(option)}>{String(option)}</option>)}</select><small>{definition.description}</small></label>;
  const numeric = definition.type === "number" || definition.type === "integer";
  return <label>{definition.label}{definition.unit ? ` (${definition.unit})` : ""}<input type={numeric ? "number" : "text"} min={definition.minimum ?? undefined} max={definition.maximum ?? undefined} step={definition.type === "integer" ? 1 : "any"} required={definition.required} value={value} onChange={(event) => onChange(event.target.value)} /><small>{definition.description}<br /><code>{definition.mapping.kind}: {definition.mapping.key}</code>{definition.toolVersionRange ? ` · ${definition.toolVersionRange}` : ""}</small></label>;
}

function sweepValues(input: SweepValue): JsonPrimitive[] {
  if (input.mode === "single") return [Number(input.single)];
  if (input.mode === "list") return [...new Set(input.list.split(",").map((value) => value.trim()).filter(Boolean).map(Number).filter(Number.isFinite))];
  const start = Number(input.start); const stop = Number(input.stop); const step = Number(input.step); const values: number[] = [];
  if (![start, stop, step].every(Number.isFinite) || step === 0 || (stop - start) * step < 0) return [];
  for (let value = start; step > 0 ? value <= stop + Math.abs(step) * 1e-9 : value >= stop - Math.abs(step) * 1e-9; value += step) { if (values.length > 10000) return []; values.push(Number(value.toPrecision(14))); }
  return values;
}

function Plan({ plan }: { plan: JobPlanV1 }): JSX.Element { return <section className="digital-plan"><div className="digital-section-heading"><div><span>Backend processing</span><h4>Planned Operations</h4></div><strong>{plan.steps.length} steps</strong></div>{plan.sweep ? <p className="digital-callout"><strong>{plan.sweep.runCount} independent sweep jobs</strong> from {Object.keys(plan.sweep.dimensions).length} dimensions; limit {plan.sweep.maxRunCount}.</p> : null}<ol>{plan.steps.map((step) => <li key={step.id}><div><strong>{step.name}</strong><p>{step.description}</p></div><div className="digital-plan__detail"><span>{step.process ? step.process.executableDisplay : "Backend validation / parser"}</span>{step.process ? <code>{step.process.argv.join(" ")}</code> : null}</div></li>)}</ol>{plan.warnings.map((warning) => <p className="digital-callout digital-callout--warning" key={warning}>{warning}</p>)}</section>; }

function Recognition({ manifest, roles }: { manifest: InputManifestV1; roles: Record<string, FileRole> }): JSX.Element { return <section className="digital-recognition"><h4>Backend recognized content</h4><p>{manifest.fileCount} files · {displayBytes(manifest.totalBytes)} · server SHA-256 recorded</p><div className="digital-table-wrap"><table><thead><tr><th>Path</th><th>Detected</th><th>Mapped use</th><th>SHA-256</th><th>Validation</th></tr></thead><tbody>{manifest.files.map((file) => <tr key={file.relativePath}><td>{file.relativePath}</td><td>{file.recognizedType}</td><td>{roles[file.relativePath] ?? "unmapped"}</td><td><code>{file.sha256.slice(0, 12)}…</code></td><td className={file.validationErrors.length || file.unresolvedIncludes.length ? "digital-status--bad" : "digital-status--ok"}>{file.validationErrors[0] ?? (file.unresolvedIncludes.length ? `Missing include: ${file.unresolvedIncludes.join(", ")}` : "Ready")}</td></tr>)}</tbody></table></div></section>; }

function Workflow({ mode, data }: { mode: Mode; data: PpaCapabilityResponse | null }): JSX.Element {
  const navigate = useNavigate(); const { user, readOnlyDemo } = useAuth(); const capabilities = data?.capabilities ?? [];
  const [flow, setFlow] = useState("openroad-orfs"); const capability = capabilities.find((item) => item.toolId === flow) ?? null;
  const [technologyId, setTechnologyId] = useState(""); const [values, setValues] = useState<Record<string, string>>({}); const [sweeps, setSweeps] = useState<Record<string, SweepValue>>({});
  const [files, setFiles] = useState<SelectedFile[]>([]); const [hashProgress, setHashProgress] = useState(0); const [uploadProgress, setUploadProgress] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [manifest, setManifest] = useState<InputManifestV1 | null>(null); const [plan, setPlan] = useState<JobPlanV1 | null>(null); const [jobId, setJobId] = useState<string | null>(null);
  useEffect(() => { if (!capability) return; setValues(Object.fromEntries(capability.parameters.map((definition) => [definition.id, definition.defaultValue === null ? "" : String(definition.defaultValue)]))); setSweeps(Object.fromEntries(capability.parameters.filter((definition) => definition.sweepable).map((definition) => [definition.id, { mode: "single", single: String(definition.defaultValue ?? ""), start: "", stop: "", step: "", list: "" }]))); setPlan(null); }, [capability]);
  const roles = useMemo(() => Object.fromEntries(files.map((item) => [item.relativePath, item.role])), [files]);
  const technologies = (data?.technologies ?? []).filter((technology) => technology.allowedAdapterIds.includes(flow));
  const sweepEntries = Object.values(sweeps); const sweepInvalid = sweepEntries.some((input) => sweepValues(input).length === 0);
  const sweepCount = sweepEntries.reduce((count, input) => count * sweepValues(input).length, 1); const maxSweep = data?.maxSweepJobs ?? 256;
  const disabled = readOnlyDemo ? "Run and Import are disabled in the read-only demo." : !user ? "Sign in to create a PPA job." : !capability ? "PPA capabilities are loading." : mode === "run" && capability.health !== "healthy" ? `${capability.label} is ${capability.health}. ${capability.healthReason ?? ""}` : sweepInvalid ? "Complete every active sweep range/list before preflight." : sweepCount > maxSweep ? `Sweep has ${sweepCount} runs; maximum is ${maxSweep}.` : null;
  const addFiles = async (added: File[]) => { setError(null); setPlan(null); setManifest(null); setJobId(null); setHashProgress(0); const selected = added.map((file) => ({ id: `${relativePath(file)}\0${file.size}\0${file.lastModified}`, file, relativePath: relativePath(file), role: inferRole(file, mode), sha256: null })); if (new Set(selected.map((item) => item.relativePath)).size !== selected.length) { setError("Duplicate relative path in selection."); return; } setFiles(selected); for (let index = 0; index < selected.length; index += 1) { const sha256 = await digest(selected[index].file); setFiles((current) => current.map((item) => item.id === selected[index].id ? { ...item, sha256 } : item)); setHashProgress((index + 1) / selected.length); } };
  const preflight = async () => { if (!files.length) return; setBusy(true); setError(null); setPlan(null); try { const draft = await createPpaDraft(mode, flow, files.map(({ file, relativePath: selectedPath }) => ({ file, relativePath: selectedPath })), (loaded, total) => setUploadProgress(total ? loaded / total : 0.5)); setManifest(draft.recognition); setJobId(draft.job.id); const parameters: Record<string, unknown> = { flow, ...Object.fromEntries((capability?.parameters ?? []).map((definition) => { const raw = values[definition.id] ?? ""; return [definition.id, definition.type === "number" || definition.type === "integer" ? Number(raw) : definition.type === "boolean" ? raw === "true" : raw]; })), technologyLibraryId: technologyId, sweep: Object.fromEntries(Object.entries(sweeps).filter(([, input]) => input.mode !== "single").map(([id, input]) => [id, input.mode === "range" ? { mode: "range", start: Number(input.start), stop: Number(input.stop), step: Number(input.step) } : { mode: "list", values: input.list.split(",").map((item) => Number(item.trim())) }])) }; const ready = await preflightPpaDraft(draft.job.id, { fileRoles: Object.fromEntries(Object.entries(roles).filter(([, role]) => role !== "ignore" || mode === "import")), parameters, technologyLibraryId: technologyId || null }); setPlan(ready.plan); setUploadProgress(1); } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); } finally { setBusy(false); } };
  const start = async () => { if (!jobId || !plan) return; setBusy(true); try { const job = await startPpaJob(jobId); navigate(`/jobs/${job.id}`); } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); setBusy(false); } };
  return <article className="digital-workflow-card ppa-workflow-card"><header><div><span className="digital-eyebrow">{mode === "run" ? "Source → physical implementation → result" : "Native run → parser → result"}</span><h3>{mode === "run" ? "Run RTL-to-GDS" : "Import Completed Run"}</h3></div><span className="digital-mode-badge">{mode === "run" ? "OpenROAD · OpenLane · LibreLane" : "Native run tree"}</span></header><p className="digital-intro">{mode === "run" ? "Choose a configured physical-design flow, map source and technology, inspect exact argv/config mappings and explicitly Start." : "Import normalized metrics or a full OpenROAD/OpenLane/LibreLane run tree. Uploaded Tcl/Make/Python remains evidence-only."}</p>
    <div className="digital-field-grid"><label>Flow<select value={flow} onChange={(event) => setFlow(event.target.value)}>{capabilities.map((item) => <option key={item.toolId} value={item.toolId}>{item.label} · {healthLabel(item)}</option>)}</select><small>{capability?.description}</small></label>{mode === "run" ? <label>Registered technology<select value={technologyId} onChange={(event) => { setTechnologyId(event.target.value); setPlan(null); }}><option value="">Select technology…</option>{technologies.map((technology) => <option key={technology.id} value={technology.id}>{technology.technologyId} · {technology.standardCellLibrary} · {technology.corner}</option>)}</select></label> : null}</div>
    {disabled ? <p className="digital-callout digital-callout--warning">{disabled}</p> : null}<section className="digital-input-section"><div className="digital-section-heading"><div><span>Step 1</span><h4>Select and map input</h4></div><strong>{files.length} files</strong></div><p className="digital-format">Single, multiple, and folder uploads preserve relative paths. RTL/gate, SDC, includes, macro Liberty/LEF/GDS and completed native evidence are supported.</p><FileButtons mode={mode} onFiles={(selected) => void addFiles(selected)} />{files.length ? <div className="digital-table-wrap"><table><thead><tr><th>Relative path</th><th>Size</th><th>SHA-256</th><th>Input mapping</th></tr></thead><tbody>{files.map((item) => <tr key={item.id}><td>{item.relativePath}</td><td>{displayBytes(item.file.size)}</td><td><code>{item.sha256 ? `${item.sha256.slice(0, 12)}…` : "Calculating…"}</code></td><td><select value={item.role} onChange={(event) => { setFiles((current) => current.map((candidate) => candidate.id === item.id ? { ...candidate, role: event.target.value as FileRole } : candidate)); setPlan(null); }}>{ROLES.map((role) => <option key={role.value} value={role.value}>{role.label}</option>)}</select></td></tr>)}</tbody></table></div> : null}{files.length ? <div className="digital-progress"><span style={{ width: `${hashProgress * 100}%` }} /><label>Local SHA-256 {Math.round(hashProgress * 100)}%</label></div> : null}</section>
    <section className="digital-parameter-section"><div className="digital-section-heading"><div><span>Step 2</span><h4>Capability parameters and sweep</h4></div><strong>{sweepCount} run{sweepCount === 1 ? "" : "s"}</strong></div><div className="digital-field-grid">{(capability?.parameters ?? []).map((definition) => <div key={definition.id} className="ppa-parameter"><ParameterInput definition={definition} value={values[definition.id] ?? ""} onChange={(value) => { setValues((current) => ({ ...current, [definition.id]: value })); setSweeps((current) => current[definition.id]?.mode === "single" ? { ...current, [definition.id]: { ...current[definition.id], single: value } } : current); setPlan(null); }} />{definition.sweepable ? <div className="ppa-sweep"><select value={sweeps[definition.id]?.mode ?? "single"} onChange={(event) => setSweeps((current) => ({ ...current, [definition.id]: { ...current[definition.id], mode: event.target.value as SweepValue["mode"] } }))}><option value="single">Single value</option><option value="range">Range</option><option value="list">Explicit list</option></select>{sweeps[definition.id]?.mode === "range" ? <div><input aria-label={`${definition.label} start`} placeholder="start" value={sweeps[definition.id].start} onChange={(event) => setSweeps((current) => ({ ...current, [definition.id]: { ...current[definition.id], start: event.target.value } }))} /><input aria-label={`${definition.label} stop`} placeholder="stop" value={sweeps[definition.id].stop} onChange={(event) => setSweeps((current) => ({ ...current, [definition.id]: { ...current[definition.id], stop: event.target.value } }))} /><input aria-label={`${definition.label} step`} placeholder="step" value={sweeps[definition.id].step} onChange={(event) => setSweeps((current) => ({ ...current, [definition.id]: { ...current[definition.id], step: event.target.value } }))} /></div> : sweeps[definition.id]?.mode === "list" ? <input placeholder="5, 10, 20" value={sweeps[definition.id].list} onChange={(event) => setSweeps((current) => ({ ...current, [definition.id]: { ...current[definition.id], list: event.target.value } }))} /> : null}</div> : null}</div>)}</div></section>
    <section className="digital-submit-section"><button className="digital-primary" type="button" disabled={busy || Boolean(disabled) || !files.length || hashProgress < 1 || (mode === "run" && !technologyId)} onClick={() => void preflight()}>{busy ? "Processing…" : "Upload & Preflight"}</button>{busy || uploadProgress ? <div className="digital-progress digital-progress--upload"><span style={{ width: `${Math.max(2, uploadProgress * 100)}%` }} /><label>Upload {Math.round(uploadProgress * 100)}%</label></div> : null}{error ? <p className="digital-callout digital-callout--error" role="alert">{error}</p> : null}</section>{manifest ? <Recognition manifest={manifest} roles={roles} /> : null}{plan ? <Plan plan={plan} /> : null}{plan ? <div className="digital-start"><div><strong>Preflight passed</strong><p>No EDA process has run. Start queues the immutable plan.</p></div><button className="digital-primary" type="button" disabled={busy} onClick={() => void start()}>Start</button></div> : null}</article>;
}

export function PpaWorkflowPanel(): JSX.Element {
  const [data, setData] = useState<PpaCapabilityResponse | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; void getPpaCapabilities().then((value) => { if (active) setData(value); }).catch((caught) => { if (active) setError(caught instanceof Error ? caught.message : String(caught)); }); return () => { active = false; }; }, []);
  return <section className="digital-workflows ppa-workflows"><div className="digital-workflows__heading"><div><span>PPA compute workspace</span><h2>Run or import a physical-design result</h2></div><p>Capabilities, versions, health, mappings and planned argv come from the backend adapters—not a frontend tool list.</p></div>{error ? <p className="digital-callout digital-callout--error">Capabilities unavailable: {error}</p> : null}<Workflow mode="run" data={data} /><Workflow mode="import" data={data} /></section>;
}
