import { useCallback, useEffect, useState, type FormEvent } from "react";
import type { TechnologyLibraryV1 } from "../../shared/contracts/v1";
import { createTechnologyLibrary, listTechnologyLibraries, updateTechnologyLibrary, type TechnologyLibraryInput } from "../api/admin";
import { formatDate, StatusBadge } from "../jobs";
import { AdminNotice } from "./AdminNotice";
import { TECHNOLOGY_ADAPTER_IDS } from "./catalog";

const EMPTY: TechnologyLibraryInput = { technologyId: "", processNode: "", pdk: "", standardCellLibrary: "", libertyPaths: [], techLefPath: null, cellLefPaths: [], corner: "", voltage: null, rcCorner: null, allowedAdapterIds: [], enabled: true };
const splitLines = (value: string) => value.split(/\r?\n/).map((line) => line.trim()).filter(Boolean);

export function TechnologyPanel(): JSX.Element {
  const [libraries, setLibraries] = useState<TechnologyLibraryV1[]>([]);
  const [selected, setSelected] = useState<TechnologyLibraryV1 | null>(null);
  const [draft, setDraft] = useState<TechnologyLibraryInput>(EMPTY);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { try { setLibraries(await listTechnologyLibraries()); setError(null); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : String(requestError)); } }, []);
  useEffect(() => { void load(); }, [load]);
  function edit(value: TechnologyLibraryV1): void { const { id: _id, revision: _revision, createdAt: _createdAt, updatedAt: _updatedAt, ...input } = value; setSelected(value); setDraft(input); setError(null); setMessage(null); }
  async function save(event: FormEvent): Promise<void> { event.preventDefault(); setBusy(true); setError(null); setMessage(null); try { const saved = selected ? await updateTechnologyLibrary(selected.id, draft) : await createTechnologyLibrary(draft); setMessage(`Saved ${saved.technologyId} revision ${saved.revision}.`); setSelected(saved); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : String(requestError)); } finally { setBusy(false); } }
  return <section className="admin-section"><header><div><h2>Technology libraries</h2><p>Register immutable PDK/library revisions and explicitly allow compatible Digital or PPA adapters.</p></div><button type="button" onClick={() => { setSelected(null); setDraft(EMPTY); }}>New technology</button></header><AdminNotice error={error} message={message} />
    <div className="admin-technology-layout"><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Technology</th><th>PDK / SCL</th><th>Corner</th><th>Adapters</th><th>State</th><th>Revision</th></tr></thead><tbody>{libraries.map((library) => <tr className={selected?.id === library.id ? "admin-table__selected" : ""} onClick={() => edit(library)} key={library.id}><td><strong>{library.technologyId}</strong><small>{library.processNode}</small></td><td>{library.pdk}<small>{library.standardCellLibrary}</small></td><td>{library.corner}<small>{library.voltage ?? "—"} V · {library.rcCorner || "RC unspecified"}</small></td><td>{library.allowedAdapterIds.join(", ") || "None"}</td><td><StatusBadge status={library.enabled ? "healthy" : "unavailable"} /></td><td>{library.revision}<small>{formatDate(library.updatedAt)}</small></td></tr>)}</tbody></table></div>
      <form className="admin-form admin-editor" onSubmit={(event) => { void save(event); }}><h3>{selected ? `Edit ${selected.technologyId}` : "Register technology"}</h3><div className="admin-form--grid"><label>Technology ID<input required value={draft.technologyId} onChange={(event) => setDraft({ ...draft, technologyId: event.target.value })} /></label><label>Process node<input required value={draft.processNode} onChange={(event) => setDraft({ ...draft, processNode: event.target.value })} /></label><label>PDK<input required value={draft.pdk} onChange={(event) => setDraft({ ...draft, pdk: event.target.value })} /></label><label>Standard-cell library<input required value={draft.standardCellLibrary} onChange={(event) => setDraft({ ...draft, standardCellLibrary: event.target.value })} /></label><label>Corner<input required value={draft.corner} onChange={(event) => setDraft({ ...draft, corner: event.target.value })} /></label><label>Voltage (V)<input type="number" step="any" value={draft.voltage ?? ""} onChange={(event) => setDraft({ ...draft, voltage: event.target.value ? Number(event.target.value) : null })} /></label><label>RC corner<input value={draft.rcCorner || ""} onChange={(event) => setDraft({ ...draft, rcCorner: event.target.value || null })} /></label><label>Tech LEF absolute path<input value={draft.techLefPath || ""} onChange={(event) => setDraft({ ...draft, techLefPath: event.target.value || null })} /></label><label className="admin-field-wide">Liberty absolute paths<textarea required rows={4} value={draft.libertyPaths.join("\n")} onChange={(event) => setDraft({ ...draft, libertyPaths: splitLines(event.target.value) })} /></label><label className="admin-field-wide">Cell LEF absolute paths<textarea rows={4} value={draft.cellLefPaths.join("\n")} onChange={(event) => setDraft({ ...draft, cellLefPaths: splitLines(event.target.value) })} /></label></div>
        <fieldset><legend>Allowed adapters</legend><p>A run is rejected when its adapter is not explicitly allowed by this technology revision.</p>{TECHNOLOGY_ADAPTER_IDS.map((adapterId) => <label className="admin-check" key={adapterId}><input type="checkbox" checked={draft.allowedAdapterIds.includes(adapterId)} onChange={(event) => setDraft({ ...draft, allowedAdapterIds: event.target.checked ? [...draft.allowedAdapterIds, adapterId] : draft.allowedAdapterIds.filter((value) => value !== adapterId) })} />{adapterId}</label>)}</fieldset><label className="admin-check admin-check--large"><input type="checkbox" checked={draft.enabled} onChange={(event) => setDraft({ ...draft, enabled: event.target.checked })} />Enabled for new preflight validations</label><button className="admin-primary" type="submit" disabled={busy || !draft.allowedAdapterIds.length}>{busy ? "Saving…" : selected ? "Save new revision" : "Register technology"}</button>
      </form></div>
  </section>;
}

